main: amao.krzysek.inviteme.InviteMe
name: InviteMe
version: 1.2
description: Recommendation system
author: krzysek
load: POSTWORLD
database: true
commands:
  inviteme:
    description: Get more informations about recommendations !
    aliases: invme
    permission: inviteme.default
    permission-message: You do not have /<permission>
  invme:
    description: Get more informations about recommendations !
    aliases: inviteme
    permission: inviteme.default
    permission-message: You do not have /<permission>
permissions:
  inviteme.default:
    description: Gives default access to commands of InviteMe plugin
    default: true
  inviteme.*:
    description: Gives super access to commands of InviteMe plugin
    default: false